SELECT COUNT(*) FROM ROUTE

SELECT * FROM ROUTE
WHERE start_airport = end_airport;

DELETE FROM ROUTE
WHERE start_airport = end_airport;


ALTER TABLE ROUTE
ALTER COLUMN distance BIGINT;

ALTER TABLE ROUTE
ALTER COLUMN base_price INT; -- Adjust precision and scale as needed

ALTER TABLE ROUTE
ALTER COLUMN duration_in_hours INT

ALTER TABLE AIRPORT
ALTER COLUMN airport_id VARCHAR(50) NOT NULL ;

ALTER TABLE ROUTE
ADD CONSTRAINT UC_Route UNIQUE (start_airport, end_airport);

ALTER TABLE ROUTE
ALTER COLUMN     ro_id VARCHAR(50)  NOT NULL

SELECT * FROM AIRPORT;
